# Generated by Django 2.2.12 on 2020-12-03 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('documento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id_carrito', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.SmallIntegerField()),
                ('precio_total', models.IntegerField()),
                ('validacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('documento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('documento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('documento_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Producto')),
                ('sabor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Producto')),
                ('peso', models.SmallIntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goma',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Producto')),
                ('sabor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CarritoCompra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.BooleanField()),
                ('credito', models.BooleanField()),
                ('debito', models.BooleanField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('expedicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.SmallIntegerField()),
                ('documento_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cliente')),
                ('documento_domiciliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Domiciliario')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCarritoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.CarritoCompra')),
                ('id_factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_cliente', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Cliente')),
                ('id_carrito_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.CarritoCompra')),
            ],
        ),
        migrations.CreateModel(
            name='ArregloChocolate',
            fields=[
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Chocolate')),
                ('precio', models.IntegerField()),
                ('tema', models.CharField(max_length=50)),
                ('expedicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso', models.SmallIntegerField()),
                ('empaque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArregloGoma',
            fields=[
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Goma')),
                ('precio', models.IntegerField()),
                ('tema', models.CharField(max_length=50)),
                ('expedicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso', models.SmallIntegerField()),
                ('empaque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CajaChocolate',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Chocolate')),
                ('categoria', models.CharField(max_length=30)),
                ('peso', models.SmallIntegerField()),
                ('expedicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiracion', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio', models.IntegerField()),
                ('unidades', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CajaGoma',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Goma')),
                ('categoria', models.CharField(max_length=30)),
                ('peso', models.SmallIntegerField()),
                ('expedicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiracion', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio', models.IntegerField()),
                ('unidades', models.SmallIntegerField()),
            ],
        ),
    ]
