# Generated by Django 2.2.12 on 2020-11-07 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id_admin', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id', models.SmallIntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='chocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fact',
            fields=[
                ('id_fact', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('id_client', models.SmallIntegerField()),
                ('d_o_exp', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_item', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shopping_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='arrag_of_gummies',
            fields=[
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.gummy')),
                ('arrag_price', models.IntegerField()),
                ('theme', models.CharField(max_length=50)),
                ('expedition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.SmallIntegerField()),
                ('package', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='box_of_chocolates',
            fields=[
                ('id_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.chocolate')),
                ('category', models.CharField(max_length=30)),
                ('weight', models.SmallIntegerField()),
                ('expedition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField()),
                ('number_of_units', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='box_of_gummies',
            fields=[
                ('id_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.gummy')),
                ('category', models.CharField(max_length=30)),
                ('weight', models.SmallIntegerField()),
                ('expedition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField()),
                ('number_of_units', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id_product', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('id_cart', models.SmallIntegerField()),
                ('product_name', models.SmallIntegerField()),
                ('unit_price', models.IntegerField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='method_of_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efective', models.BooleanField()),
                ('credit_card', models.BooleanField()),
                ('debit_card', models.BooleanField()),
                ('document_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client')),
            ],
        ),
        migrations.AddField(
            model_name='gummy',
            name='id_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.product'),
        ),
        migrations.CreateModel(
            name='flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('price_of_bouquet', models.IntegerField()),
                ('amount_of_flowers', models.SmallIntegerField()),
                ('id_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AddField(
            model_name='chocolate',
            name='id_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.product'),
        ),
        migrations.CreateModel(
            name='domc',
            fields=[
                ('id_domc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.user')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('id_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.fact')),
            ],
        ),
    ]
