# Generated by Django 2.2.12 on 2020-11-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id',
            new_name='documento',
        ),
    ]
