from django.urls import path
from . import views
urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("cliente/", views.cliente, name="cliente"),
    path("domiciliario/", views.domiciliario, name="domiciliario"),
    path("administrador/", views.administrador, name="administrador"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("perfil_cliente/", views.perfil_cliente, name="perfil_cliente"),
    path("perfil_domiciliario/", views.perfil_domiciliario, name="perfil_domiciliario"),
    path("consultar_domiciliario/", views.consultar_domiciliario, name="consultar_domiciliario"),
    path("tipo/", views.tipo, name="tipo"),
    path("arreglo_chocolate/", views.crear_arreglo_chocolate, name="arreglo_chocolate"),
    path("arreglo_chocolate1/", views.crear_arreglo_chocolate1, name="arreglo_chocolate1"),
    path("arreglo_chocolate2/", views.crear_arreglo_chocolate2, name="arreglo_chocolate2"),
    path("arreglo_goma/", views.crear_arreglo_goma, name="arreglo_goma"),
    path("arreglo_goma1/", views.crear_arreglo_goma1, name="arreglo_goma1"),
    path("arreglo_goma2/", views.crear_arreglo_goma2, name="arreglo_goma2"),
    path("caja_chocolate/", views.crear_caja_chocolate, name="caja_chocolate"),
    path("caja_chocolate1/", views.crear_caja_chocolate1, name="caja_chocolate1"),
    path("caja_chocolate2/", views.crear_caja_chocolate2, name="caja_chocolate2"),
    path("caja_goma/", views.crear_caja_goma, name="caja_goma"),
    path("caja_goma1/", views.crear_caja_goma1, name="caja_goma1"),
    path("caja_goma2/", views.crear_caja_goma2, name="caja_goma2"),
    path("flor/", views.crear_flor, name="flor"),
    path("flor1/", views.crear_flor1, name="flor1"),
    path("actualizar/<str:pk>/", views.actualizar, name="actualizar"),
    path("eliminar/<str:pk>/", views.eliminar, name="eliminar"),
    path('update_item/', views.updateItem, name="update_item"),
]